apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-product
  labels:
    app: db-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-product
  template:
    metadata:
      labels:
        app: db-product
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "TimTest123"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: db-product
spec:
  selector:
    app: db-product
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433