apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "productservice"
        dapr.io/app-port: "3200"
        dapr.io/metrics-port: "9090"
        dapr.io/sidecar-cpu-request: "100m"
        dapr.io/sidecar-cpu-limit: "500m"
        dapr.io/sidecar-memory-request: "128Mi"
        dapr.io/sidecar-memory-limit: "256Mi"
        dapr.io/sidecar-liveness-probe-delay-seconds: "15"
        dapr.io/sidecar-readiness-probe-delay-seconds: "15"
        dapr.io/sidecar-liveness-probe-timeout-seconds: "5"
        dapr.io/sidecar-liveness-probe-period-seconds: "20"
    spec:
      containers:
      - name: productservice
        image: timspitters03/tswms-productservice:dev-latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3200
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Kubernetes"
        - name: ASPNETCORE_URLS
          value: "http://+:3200"
        - name: ConnectionStrings__ProductServiceDatabase
          value: "Server=db-order;Database=ProductServiceDb;User Id=sa;Password=TimTest123;Encrypt=False;"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"